version: '3.7'
services:
  webapi:
    image: fabian986/stayathome:latest
    build: .
    container_name: webapi
    restart: on-failure
    environment: 
        - DatabaseHostName=database
    expose:
      - 5000
    ports:
      - 80:5000

  database:
    image: mongo:latest
    container_name: database
    expose:
      - 27017
    