### Send POST request with json body
POST https://creative-two.com/api/v1/player/3dea1340-e9ab-497a-b9cf-c5d40764ee05/location
Content-Type: application/json

{
  "Lat": 1,
  "Long": 1,
  "at_home": true,
  "tracked": true
}

###

### Send POST request with json body
POST https://creative-two.com/api/v1/player/3dea1340-e9ab-497a-b9cf-c5a70764ee32/location
Content-Type: application/json

{
  "Lat": 1.000005,
  "Long": 0.999999,
  "at_home": true,
  "tracked": true
}

###